const IMAGES = {
    //Dashboard
    active_buysell: require('../assets/active-buysell.png'),
    active_cropdisease: require('../assets/active-cropdisease.png'),
    active_cropsell: require('../assets/active-cropsell.png'),
    active_organic: require('../assets/tab-organic.png'),
    taborganic: require('../assets/organic.png'),
    tabhome: require('../assets/tabhome.png'),
    active_kshop: require('../assets/active-kshop.png'),
    tab_kshop: require('../assets/kshop.png'),
    active_weahterinfo: require('../assets/active-weahterinfo.png'),
    arrow_right: require('../assets/arrow-right.png'),
    backicon: require('../assets/back.png'),
    buysell: require('../assets/buysell.png'),
    call_icon: require('../assets/call.png'),
    cropdisease: require('../assets/cropdisease.png'),
    cropsell: require('../assets/cropsell.png'),
    edit_icon:require('../assets/edit.png'),
    eye_no: require('../assets/eye-no.png'),
    filter_icon:require('../assets/filterbar.png'),
    home: require('../assets/home.png'),
    icon_done: require('../assets/icon_done.png'),
    krushi_icon:require('../assets/krushi_icon.png'),
    ic_title_logo:require('../assets/ic_title_logo.png'),
    note_icon: require('../assets/shopping-list.png'),
    notification: require('../assets/notification.png'),
    profile_user: require('../assets/profileuser.png'),
    searchicon: require('../assets/search.png'),
    uploadImage: require('../assets/uploadImage.png'),
    user_octagon: require('../assets/user-octagon.png'),
    weatherinfo: require('../assets/weatherinfo.png'),
    splash_icon: require('../assets/splash_icon.png'),
    empty_wallet: require('../assets/empty_wallet.png'),
    language_switch: require('../assets/language_switch.png'),
    delete_account: require('../assets/delete_account.png'),
    wether_card: require('../assets/wetherIcon.png'),
    play_btn: require('../assets/playbtn.png'),
    upload_bill: require('../assets/uploadbill.png'),
    download: require('../assets/download.png'),
    bannercropsell: require('../assets/bannercropsell.png'),
    bannerkstore: require('../assets/bannerkstore.png'),
    greennoti: require('../assets/greennoti.png'),
    placeholder: require('../assets/placeholder.png'),
    placeholderbg: require('../assets/gradianbg.png'),
    tractor: require('../assets/tractor.json'),
    all: require('../assets/all.png'),
    Success: require('../assets/Success.json'),
    Right: require('../assets/right.png'),
    Left: require('../assets/left.png'),
    company_icon: require('../assets/company_icon.png'),
    farmer_icon: require('../assets/farmer_icon.png'),
    cart: require('../assets/cart.png'),
  };
  
  export default IMAGES;